use `huo`;

CREATE TABLE IF NOT EXISTS `SimpleEntity`
(
    `id`    VARCHAR(36) PRIMARY KEY,
    `date`  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    `clazz` VARCHAR(36) DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `who`   VARCHAR(36) NOT NULL
);


CREATE TABLE IF NOT EXISTS `Tables`
(
    `id`    VARCHAR(36) PRIMARY KEY
);
