
name: Images and tags cleanup

on:
  pull_request:

env:
  ORG: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}
  PR_NUMBER: ${{ github.event.number }}

jobs:

  tag:
    name: Tag
    runs-on: ubuntu-latest
    concurrency:
      group: tag
      cancel-in-progress: false
    outputs:
      new_tag: ${{ steps.pushtag.outputs.new_tag }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Push new tag
        id: pushtag
        # v1.38.0 does not work (see issue https://github.com/anothrNick/github-tag-action/issues/135)
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: PATCH
          PRERELEASE_SUFFIX: PR${{ env.PR_NUMBER }}

      - name: Add tag to summary
        run: echo 'Tag `${{ steps.pushtag.outputs.new_tag }}`' >> $GITHUB_STEP_SUMMARY

  get_tags:
    needs: tag
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Tags PR just merged
        id: tags_list
        run: |
          printf -v tags_string '"%s",' $(git tag -l "*PR${{ env.PR_NUMBER }}*")
          tags_list=$(echo "[${tags_string%,}]")
          echo "$tags_list"
          echo "::set-output name=value::$tags_list"

      - name: set tags list output
        id: matrix
        run: |
          echo ${{ steps.tags_list.outputs.value }}
          echo '::set-output name=value::${{ steps.tags_list.outputs.value }}'

  delete_image:
    needs: get_tags
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        value: ${{ fromJson(needs.get_tags.outputs.matrix) }}
    steps:
      -
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.1
        with:
          owner: ${{ env.ORG }}
          name: ${{ env.REPOSITORY }}
          token: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ matrix.value }}

      - name: Delete tag
        run: git push -d origin ${{ matrix.value }}
