---
name: Images and tags cleanup

on:
  pull_request:
    types: [closed]

env:
  ORG: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}
  PR_NUMBER: ${{ github.event.number }}

jobs:
  get_tags:
    name: Get PR tags
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Tags PR just merged
        id: tags_list
        run: |
          printf -v tags_string '"%s",' $(git tag -l "*PR${{ env.PR_NUMBER }}*")
          tags_list=$(echo "[${tags_string%,}]")
          echo "$tags_list"
          echo "value=$tags_list" >> $GITHUB_OUTPUT

      - name: set tags list output
        id: matrix
        run: |
          echo ${{ steps.tags_list.outputs.value }}
          echo "value=${{ toJson(steps.tags_list.outputs.value) }}" >> $GITHUB_OUTPUT

  delete:
    name: Delete tags and images
    needs: get_tags
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}

    strategy:
      matrix:
        value: ${{ fromJson(needs.get_tags.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3

      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.1
        with:
          owner: ${{ env.ORG }}
          name: ${{ env.REPOSITORY }}
          token: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ matrix.value }}

      - name: Delete tag
        run: |
          git fetch --tags
          git push -d origin ${{ matrix.value }}
