
name: Lint

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: lint
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:dry
