
name: Lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  checks: write
  contents: read

concurrency:
  group: lint
  cancel-in-progress: true

jobs:
  lint-typescript:
    name: Lint Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'

  lint-dockerfile:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
          level: warning
          fail_on_error: true

  lint-actions:
    name: Lint Github actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Github Actions
        uses: reviewdog/action-actionlint@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reporter: github-pr-review
