
name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: pipeline-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      report: ${{ steps.issues_report.outputs.report }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile project
        run: npm run compile

      - name: Lint
        run: npm run lint:dry

      - name: Run tests
        run: npm run test:init && npm test

      - name: Code coverage
        run: npm run coverage

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
