
name: Pipeline test

on:
  pull_request:

concurrency:
  group: pipeline-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start test database
        run: docker run -d --rm --name huo-mysql -p 3399:3306 -e MYSQL_DATABASE=huo -e MYSQL_USER=huo_app -e MYSQL_PASSWORD=test -e MYSQL_RANDOM_ROOT_PASSWORD=true -v $(pwd)/scripts/mysql:/docker-entrypoint-initdb.d mysql:8

      - name: Node setup
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for db initialization
        run: sleep 10

      - name: Run tests
        run: npm run test:init && npm test

      - name: Code coverage
        run: npm run coverage

      - name: Stop test database
        run: docker container rm -f huo-mysql

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:dry
