---
name: Unit tests

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: unit-tests
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start test database
        run: docker run -d --rm --name huo-db -p 3399:3306 -e MYSQL_DATABASE=huo -e MYSQL_USER=huo_app -e MYSQL_PASSWORD=test -e MYSQL_RANDOM_ROOT_PASSWORD=true -v $(pwd)/scripts/mysql:/docker-entrypoint-initdb.d mysql:8

      - name: Node setup
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for db initialization
        run: sleep 10

      - name: Run tests
        run: npm run test:init && npm test

      - name: Stop test database
        run: docker container rm -f huo-mysql

      - name: Code coverage
        run: npm run coverage

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
